// Builds data/schedule.js from the verified 2026 WRL Autumn fixture list.
"use strict";

const fs = require("fs");
const path = require("path");
const { teams: teamCodes, matches: rawMatches, run } = require("./check_schedule.js");

if (!run()) process.exit(1);

const root = path.join(__dirname, "..");

const weeks = [
    { week: 1, title: "第 1 周（8.21–8.23）", dates: ["08-21", "08-22", "08-23"] },
    { week: 2, title: "第 2 周（8.28–8.30）", dates: ["08-28", "08-29", "08-30"] },
    { week: 3, title: "第 3 周（9.4–9.6）", dates: ["09-04", "09-05", "09-06"] },
    { week: 4, title: "第 4 周（9.11–9.13）", dates: ["09-11", "09-12", "09-13"] },
    { week: 5, title: "第 5 周（9.18–9.20）", dates: ["09-18", "09-19", "09-20"] },
    { week: 6, title: "第 6 周（9.25–9.27）", dates: ["09-25", "09-26", "09-27"] },
    { week: 7, title: "第 7 周（10.2–10.4）", dates: ["10-02", "10-03", "10-04"] }
];

const weekByDate = {};
for (const w of weeks) {
    for (const d of w.dates) weekByDate[d] = w.week;
}

const teams = teamCodes.map(code => ({
    id: code,
    name: code,          // 全名待站主补充
    short: code,
    region: "",
    logo: ""
}));

const rounds = weeks.map(w => {
    const wMatches = rawMatches
        .filter(m => weekByDate[m[0]] === w.week)
        .sort((a, b) => (a[0] + a[1]).localeCompare(b[0] + b[1]))
        .map((m, i) => ({
            id: "W" + w.week + "M" + (i + 1),
            date: "2026-" + m[0] + " " + m[1],
            timezone: "UTC+8",
            bestOf: 3,
            opponent1: m[2],
            opponent2: m[3],
            mvp: [],
            vod: "",
            youtube: "",
            twitch: "",
            games: []
        }));
    return {
        id: "week" + w.week,
        patch: ["7.2c", "7.2d", "7.2d", "7.2e", "7.2e", "7.3", "7.3"][w.week - 1],
        completed: w.week <= 5,
        title: w.title,
        date: "2026-" + w.dates[0],
        matches: wMatches
    };
});

const league = {
    meta: {
        name: "2026 英雄联盟手游超级联赛秋季赛",
        nameEn: "2026 Wild Rift League Autumn",
        ticker: "WRL 2026 Autumn",
        startDate: "2026-08-21",
        endDate: "2026-10-04",
        patch: "7.2（第 1–5 周） / 7.3（第 6 周起）",
        organizer: "待填写",
        venue: "待填写",
        prize: "待填写",
        website: "",
        teamsCount: 8,
        playoffTeams: 4,
        eliminatedTeams: 4,
        demo: false,
        formatText: [
            "**小组赛**：8 支队伍进行双循环 BO3，每两支队伍交手两次（主客场各一次），共 56 个大场。",
            "**双边无畏征召（Fearless Draft）**：同一大场内，双方已选用的英雄在该大场后续小局中均不可再选；禁用按小局独立进行。",
            "排名先按大场胜场数，再依次比较大场净胜、小场胜场、小场净胜；前 4 名晋级季后赛。",
            "**BP 率口径**：某英雄在一个大场中被任一方首次选用后，该大场后续小局不再计入该英雄的 BP 率分母；若整个大场未被选用，则全部小局计入分母。"
        ]
    },
    teams,
    rounds
};

const header = `// ============================================================
// WRpedia schedule data - edit this file, then refresh the page.
// Generated by tools/build_schedule.js from the verified fixture list.
// ============================================================
// Keep the outer "window.WR_LEAGUE = ...;" line intact.
//
// teams: 8 entries. "id" is referenced by matches (keep stable);
//   "name" full name (currently abbreviation, fill in later),
//   "short" abbreviation, "logo" optional image URL,
//   "region" optional.
//
// rounds: patch = tournament patch; completed = week finished (results may be pending).
// A match can override round.patch with its own patch.
// rounds: 7 weeks, 8 matches each. A match:
//   id, date ("2026-08-21 17:00"), timezone, bestOf (3),
//   opponent1/opponent2 (team ids), mvp (array of strings),
//   vod/youtube/twitch (optional URLs), games (array).
// A game:
//   length ("18:32"), winner (1 = opponent1, 2 = opponent2),
//   team1/team2: { side: "blue"|"red", picks: [5 slugs], bans: [5 slugs] }
//
// Champion slugs live in data/champions.json. In the browser console:
//   Object.keys(WR.champions)
// lists every slug.
// ============================================================

`;

const json = JSON.stringify(league, null, 2);
const content = header + "window.WR_LEAGUE = " + json + ";" + "\n";
const out = path.join(root, "data", "schedule.js");
fs.writeFileSync(out, content, "utf8");

const matchCount = rounds.reduce((n, r) => n + r.matches.length, 0);
console.log("Generated " + out);
console.log("Teams: " + teams.length + ", rounds: " + rounds.length + ", matches: " + matchCount);
